baseURL = "http://robertzmay.com/curves-documentation/"
languageCode = "en-us"
title = "Curves Documentation"
theme = "ace-documentation"
pygmentsCodeFences = true
pygmentsStyle = "manni"
publishdir = "build"

[[menu.shortcuts]]
name = "Demos"
url = "http://robertzmay.com/curves-demo/"
weight = 8

[[menu.shortcuts]]
name = "<i class='fab fa-npm'></i>"
url = "https://www.npmjs.com/package/curves"
weight = 9

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i>"
url = "https://github.com/robertmay2003/curves"
weight = 10

[markup.goldmark.renderer]
unsafe = true